### ISSUE TITLE
Phase 2 Todos

### ISSUE THREAD

**Issue by TheAwiteb** [TheAwiteb/restful_todo#13]
## Todos CRUDS 🔍 📍 
- [x] Create a todo `/api/todos` _`POST`_
    - [x] Test.
    - [x] Docs.
- [x] Get todo by id`/api/todos/{id}` _`GET`_
    - [x] Test.
    - [x] Docs.
- [x] List user todos (With the possibility of searching through queries) `/api/todos` _`GET`_
    - [x] Test.
    - [x] Docs.
- [x] Update todo `/api/todos/{id}` _`PUT`_
    - [x] Test.
    - [x] Docs.
- [x] Delete todo by id `/api/todos/{id}` _`DELETE`_
    - [x] Test.
    - [x] Docs.
- [x] Delete all todos `/api/todos` _`DELETE`_
    - [x] Test.
    - [x] Docs.
