### ISSUE TITLE
API Roadmap

### ISSUE THREAD

**Issue by TheAwiteb** [TheAwiteb/restful_todo#5]
#### Authentication

- [X] Auth register. `/api/auth/register` _`POST`_
    - [x] Test.
    - [X] Docs.
- [X] Auth login. `/api/auth/login` _`POST`_
    - [x] Test.
    - [X] Docs.
- [X] Auth token revoke. `/api/auth/revoke` _`PATCH`_
    - [x] Test.
    - [X] Docs.
